name: Set Custom API URL Secret

on:
  push:
    branches:
      - main

jobs:
  set_secret:
    runs-on: ubuntu-latest
    steps:
      - name: Set Custom API URL Secret
        uses: actions/checkout@v2
      - name: Set Secret
        run: echo "CUSTOM_API_URL=$CUSTOM_API_URL" >> $GITHUB_ENV
